# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a91da74c8aa893b7f3a8af812f1b8c80c89206a153751945424f73872c97a529703786c32303e7f1dcc76e6dd369c5fc036eb3d34dba7bf4039c8829df400636

test:
  secret_key_base: d671a4305a0553d3f52ed995a32bad2543931ff6a5f43fec0a904fa80c9d96e271479694ab62f29ae985bb3d9866e03cfe9335d25874044bf8a40c46bea8c83a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
